_target_: src.model.HiFiGAN
Generator:
  _target_: src.model.Generator
  in_channels: 80
  hidden_dim: 128
  kernels: [ 16, 16, 4, 4 ]
  mrf_kernels: [ 3, 7, 11 ]
  mrf_dilation: [ [ [ 1, 1 ], [ 3, 1 ], [ 5, 1 ] ] ,  [ [ 1, 1 ], [ 3, 1 ], [ 5, 1 ] ] ,  [ [ 1, 1 ], [ 3, 1 ], [ 5, 1 ] ] ]
MultiPeriodDiscriminator:
  _target_: src.model.MultiPeriodDiscriminator
  p: [ 2, 3, 5, 7, 11 ]

MultiScaleDiscriminator:
  _target_: src.model.MultiScaleDiscriminator
